;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Unlocked.Companions.Mouse",NewTagName="Unlocked.Companions.MrDent")
+GameplayTagRedirects=(OldTagName="Regional.Caverns.CMAttack",NewTagName="Regional.Caverns.CMFight")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers",NewTagName="Equipped.Amber")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Bonk",NewTagName="Equipped.Amber.Bonk")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Brace",NewTagName="Equipped.Amber.Brace")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.BrokenGlasses",NewTagName="Equipped.Amber.BrokenGlasses")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Droplet",NewTagName="Equipped.Amber.Droplet")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Harden",NewTagName="Equipped.Amber.Harden")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.HaresEars",NewTagName="Equipped.Amber.HaresEars")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Herb",NewTagName="Equipped.Amber.Herb")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Hone",NewTagName="Equipped.Amber.Hone")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Infectious",NewTagName="Equipped.Amber.Infectious")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Preserve",NewTagName="Equipped.Amber.Preserve")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Pointy",NewTagName="Equipped.Amber.Pointy")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Reinforcements",NewTagName="Equipped.Amber.Reinforcements")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Shiny",NewTagName="Equipped.Amber.Shiny")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Sharpen",NewTagName="Equipped.Amber.Sharpen")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Translation",NewTagName="Equipped.Amber.Translation")
+GameplayTagRedirects=(OldTagName="Equipped.Ambers.Wheel",NewTagName="Equipped.Amber.Wheel")
+GameplayTagRedirects=(OldTagName="Equipped.Companions",NewTagName="Equipped.Companion")
+GameplayTagRedirects=(OldTagName="Equipped.Companions.Dove",NewTagName="Equipped.Companion.Dove")
+GameplayTagRedirects=(OldTagName="Equipped.Companions.MrDent",NewTagName="Equipped.Companion.MrDent")
+GameplayTagRedirects=(OldTagName="Equipped.Weapons",NewTagName="Equipped.Weapon")
+GameplayTagRedirects=(OldTagName="Equipped.Weapons.BoneAxe",NewTagName="Equipped.Weapon.BoneAxe")
+GameplayTagRedirects=(OldTagName="Equipped.Weapons.CopperDagger",NewTagName="Equipped.Weapon.CopperDagger")
+GameplayTagRedirects=(OldTagName="Equipped.Weapons.RatSword",NewTagName="Equipped.Weapon.RatSword")
+GameplayTagRedirects=(OldTagName="Equipped.Weapons.RuneHammer",NewTagName="Equipped.Weapon.RuneHammer")
+GameplayTagRedirects=(OldTagName="Equipped.Weapons.TailWhip",NewTagName="Equipped.Weapon.TailWhip")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers",NewTagName="Unlocked.Amber")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Bonk",NewTagName="Unlocked.Amber.Bonk")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Brace",NewTagName="Unlocked.Amber.Brace")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.BrokenGlasses",NewTagName="Unlocked.Amber.BrokenGlasses")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Droplet",NewTagName="Unlocked.Amber.Droplet")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Harden",NewTagName="Unlocked.Amber.Harden")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Herb",NewTagName="Unlocked.Amber.Herb")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.HaresEars",NewTagName="Unlocked.Amber.HaresEars")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Hone",NewTagName="Unlocked.Amber.Hone")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Infectious",NewTagName="Unlocked.Amber.Infectious")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Pointy",NewTagName="Unlocked.Amber.Pointy")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Preserve",NewTagName="Unlocked.Amber.Preserve")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Reinforcements",NewTagName="Unlocked.Amber.Reinforcements")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Sharpen",NewTagName="Unlocked.Amber.Sharpen")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Shiny",NewTagName="Unlocked.Amber.Shiny")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Translation",NewTagName="Unlocked.Amber.Translation")
+GameplayTagRedirects=(OldTagName="Unlocked.Ambers.Wheel",NewTagName="Unlocked.Amber.Wheel")
+GameplayTagRedirects=(OldTagName="Unlocked.Companions",NewTagName="Unlocked.Companion")
+GameplayTagRedirects=(OldTagName="Unlocked.Companions.Dove",NewTagName="Unlocked.Companion.Dove")
+GameplayTagRedirects=(OldTagName="Unlocked.Companions.MrDent",NewTagName="Unlocked.Companion.MrDent")
+GameplayTagRedirects=(OldTagName="Unlocked.Weapons",NewTagName="Unlocked.Weapon")
+GameplayTagRedirects=(OldTagName="Unlocked.Weapons.BoneAxe",NewTagName="Unlocked.Weapon.BoneAxe")
+GameplayTagRedirects=(OldTagName="Unlocked.Weapons.CopperDagger",NewTagName="Unlocked.Weapon.CopperDagger")
+GameplayTagRedirects=(OldTagName="Unlocked.Weapons.RatSword",NewTagName="Unlocked.Weapon.RatSword")
+GameplayTagRedirects=(OldTagName="Unlocked.Weapons.RuneHammer",NewTagName="Unlocked.Weapon.RuneHammer")
+GameplayTagRedirects=(OldTagName="Unlocked.Weapons.TailWhip",NewTagName="Unlocked.Weapon.TailWhip")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16

